#[path = "07e_ai_batch_builder.rs"]
pub mod ai_batch_builder;
#[path = "07_ai_core.rs"]
pub mod ai_core;
#[path = "07b_ai_gemini.rs"]
pub mod ai_gemini;
#[path = "07d_ai_rate_limiter.rs"]
pub mod ai_rate_limiter;
#[path = "08_config.rs"]
pub mod config;
#[path = "12_auth.rs"]
pub mod auth;
#[path = "06_data_ingestion.rs"]
pub mod data_ingestion;
#[path = "01b_db_repo.rs"]
pub mod db_repo;
#[path = "01_db_setup.rs"]
pub mod db_setup;
#[path = "01c_db_traits.rs"]
pub mod db_traits;
#[path = "04_downloader.rs"]
pub mod downloader;
#[path = "05_json_extractor.rs"]
pub mod json_extractor;
#[path = "00_models.rs"]
pub mod models;
#[path = "06b_pipeline_orchestrator.rs"]
pub mod pipeline_orchestrator;
#[path = "14_scheduler.rs"]
pub mod scheduler;
#[path = "03_scraper_roche.rs"]
pub mod scraper_roche;
#[path = "02_web_core.rs"]
pub mod web_core;
#[path = "11_web_server.rs"]
pub mod web_server;
#[path = "13_web_ui.rs"]
pub mod web_ui;
